# CMake generated Testfile for 
# Source directory: C:/mnich2/OpenIGTLink-1/Testing
# Build directory: C:/mnich2/OpenIGTLink-1/Blds/Testing
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(igtlMultiThreaderTest1 "C:/mnich2/OpenIGTLink-1/Blds/bin/igtlMultiThreaderTest1")
add_test(igtlMultiThreaderTest2 "C:/mnich2/OpenIGTLink-1/Blds/bin/igtlMultiThreaderTest2")
add_test(igtlMultiThreaderTest3 "C:/mnich2/OpenIGTLink-1/Blds/bin/igtlMultiThreaderTest3")
add_test(igtlMessageFactoryTest "C:/mnich2/OpenIGTLink-1/Blds/bin/igtlMessageFactoryTest")
add_test(igtlTimeStampTest1 "C:/mnich2/OpenIGTLink-1/Blds/bin/igtlTimeStampTest1")
add_test(igtlMessageBaseTest "C:/mnich2/OpenIGTLink-1/Blds/bin/igtlMessageBaseTest" "--gtest_filter=*.*FormatVersion1")
add_test(igtlConditionVariableTest "C:/mnich2/OpenIGTLink-1/Blds/bin/igtlConditionVariableTest" "--gtest_filter=*.*FormatVersion1")
add_test(igtlImageMessageTest "C:/mnich2/OpenIGTLink-1/Blds/bin/igtlImageMessageTest" "--gtest_filter=*.*FormatVersion1")
add_test(igtlImageMessage2Test "C:/mnich2/OpenIGTLink-1/Blds/bin/igtlImageMessage2Test" "--gtest_filter=*.*FormatVersion1")
add_test(igtlCapabilityMessageTest "C:/mnich2/OpenIGTLink-1/Blds/bin/igtlCapabilityMessageTest" "--gtest_filter=*.*FormatVersion1")
add_test(igtlStatusMessageTest "C:/mnich2/OpenIGTLink-1/Blds/bin/igtlStatusMessageTest" "--gtest_filter=*.*FormatVersion1")
add_test(igtlTransformMessageTest "C:/mnich2/OpenIGTLink-1/Blds/bin/igtlTransformMessageTest" "--gtest_filter=*.*FormatVersion1")
add_test(igtlPositionMessageTest "C:/mnich2/OpenIGTLink-1/Blds/bin/igtlPositionMessageTest")
add_test(igtlBindMessageTest "C:/mnich2/OpenIGTLink-1/Blds/bin/igtlBindMessageTest" "--gtest_filter=*.*FormatVersion1")
add_test(igtlColorTableMessageTest "C:/mnich2/OpenIGTLink-1/Blds/bin/igtlColorTableMessageTest" "--gtest_filter=*.*FormatVersion1")
add_test(igtlLabelMetaMessageTest "C:/mnich2/OpenIGTLink-1/Blds/bin/igtlLabelMetaMessageTest" "--gtest_filter=*.*FormatVersion1")
add_test(igtlNDArrayMessageTest "C:/mnich2/OpenIGTLink-1/Blds/bin/igtlNDArrayMessageTest" "--gtest_filter=*.*FormatVersion1")
add_test(igtlImageMetaMessageTest "C:/mnich2/OpenIGTLink-1/Blds/bin/igtlLabelMetaMessageTest" "--gtest_filter=*.*FormatVersion1")
add_test(igtlPointMessageTest "C:/mnich2/OpenIGTLink-1/Blds/bin/igtlPointMessageTest" "--gtest_filter=*.*FormatVersion1")
add_test(igtlPolyDataMessageTest "C:/mnich2/OpenIGTLink-1/Blds/bin/igtlPolyDataMessageTest" "--gtest_filter=*.*FormatVersion1")
add_test(igtlSensorMessageTest "C:/mnich2/OpenIGTLink-1/Blds/bin/igtlSensorMessageTest" "--gtest_filter=*.*FormatVersion1")
add_test(igtlStringMessageTest "C:/mnich2/OpenIGTLink-1/Blds/bin/igtlStringMessageTest" "--gtest_filter=*.*FormatVersion1")
add_test(igtlTrackingDataMessageTest "C:/mnich2/OpenIGTLink-1/Blds/bin/igtlTrackingDataMessageTest" "--gtest_filter=*.*FormatVersion1")
add_test(igtlTrajectoryMessageTest "C:/mnich2/OpenIGTLink-1/Blds/bin/igtlTrajectoryMessageTest" "--gtest_filter=*.*FormatVersion1")
add_test(igtlMessageBaseTestFormatVersion2 "C:/mnich2/OpenIGTLink-1/Blds/bin/igtlMessageBaseTest" "--gtest_filter=*.*FormatVersion2")
add_test(igtlImageMessageTestFormatVersion2 "C:/mnich2/OpenIGTLink-1/Blds/bin/igtlImageMessageTest" "--gtest_filter=*.*FormatVersion2")
add_test(igtlImageMessage2TestFormatVersion2 "C:/mnich2/OpenIGTLink-1/Blds/bin/igtlImageMessage2Test" "--gtest_filter=*.*FormatVersion2")
add_test(igtlBindMessageTestFormatVersion2 "C:/mnich2/OpenIGTLink-1/Blds/bin/igtlBindMessageTest" "--gtest_filter=*.*FormatVersion2")
add_test(igtlCapabilityMessageTestFormatVersion2 "C:/mnich2/OpenIGTLink-1/Blds/bin/igtlCapabilityMessageTest" "--gtest_filter=*.*FormatVersion2")
add_test(igtlColorTableMessageTestFormatVersion2 "C:/mnich2/OpenIGTLink-1/Blds/bin/igtlColorTableMessageTest" "--gtest_filter=*.*FormatVersion2")
add_test(igtlConditionVariableTestFormatVersion2 "C:/mnich2/OpenIGTLink-1/Blds/bin/igtlConditionVariableTest" "--gtest_filter=*.*FormatVersion2")
add_test(igtlLabelMetaMessageTestFormatVersion2 "C:/mnich2/OpenIGTLink-1/Blds/bin/igtlLabelMetaMessageTest" "--gtest_filter=*.*FormatVersion2")
add_test(igtlNDArrayMessageTestFormatVersion2 "C:/mnich2/OpenIGTLink-1/Blds/bin/igtlNDArrayMessageTest" "--gtest_filter=*.*FormatVersion2")
add_test(igtlImageMetaMessageTestFormatVersion2 "C:/mnich2/OpenIGTLink-1/Blds/bin/igtlLabelMetaMessageTest" "--gtest_filter=*.*FormatVersion2")
add_test(igtlPointMessageTestFormatVersion2 "C:/mnich2/OpenIGTLink-1/Blds/bin/igtlPointMessageTest" "--gtest_filter=*.*FormatVersion2")
add_test(igtlPolyDataMessageTestFormatVersion2 "C:/mnich2/OpenIGTLink-1/Blds/bin/igtlPolyDataMessageTest" "--gtest_filter=*.*FormatVersion2")
add_test(igtlSensorMessageTestFormatVersion2 "C:/mnich2/OpenIGTLink-1/Blds/bin/igtlSensorMessageTest" "--gtest_filter=*.*FormatVersion2")
add_test(igtlStatusMessageTestFormatVersion2 "C:/mnich2/OpenIGTLink-1/Blds/bin/igtlStatusMessageTest" "--gtest_filter=*.*FormatVersion2")
add_test(igtlStringMessageTestFormatVersion2 "C:/mnich2/OpenIGTLink-1/Blds/bin/igtlStringMessageTest" "--gtest_filter=*.*FormatVersion2")
add_test(igtlTrackingDataMessageTestFormatVersion2 "C:/mnich2/OpenIGTLink-1/Blds/bin/igtlTrackingDataMessageTest" "--gtest_filter=*.*FormatVersion2")
add_test(igtlTrajectoryMessageTestFormatVersion2 "C:/mnich2/OpenIGTLink-1/Blds/bin/igtlTrajectoryMessageTest" "--gtest_filter=*.*FormatVersion2")
add_test(igtlTransformMessageTestFormatVersion2 "C:/mnich2/OpenIGTLink-1/Blds/bin/igtlTransformMessageTest" "--gtest_filter=*.*FormatVersion2")
add_test(igtlCommandMessageTestFormatVersion1 "C:/mnich2/OpenIGTLink-1/Blds/bin/igtlCommandMessageTest" "--gtest_filter=*.*FormatVersion1")
add_test(igtlCommandMessageTestFormatVersion2 "C:/mnich2/OpenIGTLink-1/Blds/bin/igtlCommandMessageTest" "--gtest_filter=*.*FormatVersion2")
subdirs(igtlutil)
subdirs(gmock-build)
